import { createApp } from 'vue';
import {
  Button,
  Cell,
  CellGroup,
  Field,
  Toast,
  Dialog,
  Notify,
  Loading,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Switch,
  Slider,
  Uploader,
  ActionSheet,
  Popup,
  PullRefresh,
  List,
  SwipeCell,
  Grid,
  GridItem,
  IndexBar,
  IndexAnchor,
  Sticky,
  NavBar,
  Tabbar,
  TabbarItem,
  Tab,
  Tabs,
  Collapse,
  CollapseItem,
  Picker,
  DatePicker,
  Calendar,
  Image,
  Lazyload,
  CountDown,
  Steps,
  Step,
  Tag,
  Badge,
  Progress,
  Overlay,
  Empty,
  NoticeBar,
  Skeleton,
  Divider,
  Space,
  Rate,
  Search,
  ShareSheet,
  ContactList,
  ContactCard,
  Area,
  Card
} from 'vant';

// 导出Vant组件注册函数
export function registerVant(app) {
  app.use(Button);
  app.use(Cell);
  app.use(CellGroup);
  app.use(Field);
  app.use(Toast);
  app.use(Dialog);
  app.use(Notify);
  app.use(Loading);
  app.use(Radio);
  app.use(RadioGroup);
  app.use(Checkbox);
  app.use(CheckboxGroup);
  app.use(Switch);
  app.use(Slider);
  app.use(Uploader);
  app.use(ActionSheet);
  app.use(Popup);
  app.use(PullRefresh);
  app.use(List);
  app.use(SwipeCell);
  app.use(Grid);
  app.use(GridItem);
  app.use(IndexBar);
  app.use(IndexAnchor);
  app.use(Sticky);
  app.use(NavBar);
  app.use(Tabbar);
  app.use(TabbarItem);
  app.use(Tab);
  app.use(Tabs);
  app.use(Collapse);
  app.use(CollapseItem);
  app.use(Picker);
  app.use(DatePicker);
  app.use(Calendar);
  app.use(Image);
  app.use(Lazyload);
  app.use(CountDown);
  app.use(Steps);
  app.use(Step);
  app.use(Tag);
  app.use(Badge);
  app.use(Progress);
  app.use(Overlay);
  app.use(Empty);
  app.use(NoticeBar);
  app.use(Skeleton);
  app.use(Divider);
  app.use(Space);
  app.use(Rate);
  app.use(Search);
  app.use(ShareSheet);
  app.use(ContactList);
  app.use(ContactCard);
  app.use(Area);
  app.use(Card);
}
